### ISSUE TITLE
No Tiles.txt file

### ISSUE THREAD

**Issue by alonyan** [VolkerH/Ultramicroscope2BigStitcher#7]
Hi Volker, 

Would it be possible to have a gentler fallback in case there is no tiles.txt file? Something like putting all the tiles at (0,0,0) which is BigStitcher's default behavior. This will be especially useful in cases where there's only a single tile.

Thanks for this potentially very useful software!

**Comment by VolkerH** [comment]
Sorry for the late reply @alonyan, I was away on holiday and therefore overlooked the notfiication for this issue.
That sounds like a very reasonable suggestion. 
If this is something you can add yourself, I would welcome a pull request.
Otherwise, please let me know whether this is still of interest and I will see if I can add it. 
I am currently not working with Ultramicroscope data anymore.
